{circumference: 230, description: 'CAT Vehicle Simulation:1Car, Iteration 0 ID 1e889999-ce23-4e6f-b5af-ac7ce3380f10',
  include_laser: false, log_time: 300.0, logdir: /home/ivory/CyverseData/ProjectSparkle,
  max_update_rate: 100.0, n_vehicles: 1, package_name: catvehicle, time_step: 0.01,
  update_rate: 100.0}
