{circumference: 230, description: 'CAT Vehicle Simulation:1Car, Iteration 0 ID 17c9f31f-4a80-44c6-beb3-819bacafad67',
  include_laser: false, log_time: 300.0, logdir: /home/reu-cat/CyverseData/ProjectSparkle,
  max_update_rate: 100.0, n_vehicles: 1, time_step: 0.01, update_rate: 20.0}
