{circumference: 230, description: 'CAT Vehicle Simulation:1Car, Iteration 0 ID c0dcc6ac-e7c6-4721-94c1-1e771a158042',
  include_laser: false, log_time: 300.0, logdir: /home/ivory/CyverseData/ProjectSparkle,
  max_update_rate: 100.0, n_vehicles: 1, time_step: 0.01, update_rate: 20.0}
